modLoader = "javafml"
loaderVersion = "[47,)" # Forge 1.20.1
license = "MIT"

[[mods]]
modId = "thermaltinkersmod"
version = "1.0.0"
displayName = "Thermal Tinkers"
authors = "Slurmpy"
description = '''
Adds Tough As Nails compatibility to Tinkers' Construct: thermal modifiers, upgrades, and more!
'''

[[dependencies.thermaltinkersmod]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thermaltinkersmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thermaltinkersmod]]
modId = "mantle"
mandatory = true
versionRange = "[1.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thermaltinkersmod]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.9.1.19,)"
ordering = "NONE"
side = "BOTH"
